name: Build & Publish .NET App

on:
  push:
    branches: [ mater ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # You can switch to windows-latest if needed

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1' # or '3.1.x' / '8.0.x' as required by your project

      - name: 🧰 Install 7-Zip CLI (Linux)
        run: sudo apt update && sudo apt install -y p7zip-full

      - name: 🚀 Run PowerShell build script
        shell: pwsh
        run: ./BGServiceAX/build.ps1
        working-directory: ./BGServiceAX
        
      - name: 📦 Upload ZIP as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: AXAPIWrapper-Zip
          path: ./publish/*.zip
