name: Build & Publish .NET App

env:
  BUILD_DIR: ./BGServiceAX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET SDK 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: 🧰 Install 7-Zip CLI (Linux)
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: 🚀 Run PowerShell build script
        shell: pwsh
        run: ./build.ps1
        working-directory: ${{ env.BUILD_DIR }}

      - name: 📦 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AXAPIWrapper-Zip
          path: ${{ env.BUILD_DIR }}/publish/*.zip
